name: 'Deploy GitHub Pages'
description: 'Builds and deploys a web application or documentation to GitHub Pages'

inputs:
  build-command:
    description: 'Command to build the project/docs'
    required: false
    default: 'npm run build'
  dist-path:
    description: 'Path to the built artifacts'
    required: false
    default: './dist'

runs:
  using: "composite"
  steps:
    - name: Setup Pages
      uses: actions/configure-pages@v4
      with:
        static_site_generator: 'vite'

    - name: Build
      if: inputs.build-command != ''
      run: ${{ inputs.build-command }}
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ inputs.dist-path }}

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
