name: Publish Plugin

on:
  workflow_call:
    inputs:
      version:
        description: 'The version being published'
        required: true
        type: string
      plugin_name:
        description: 'The folder name of the plugin inside the plugins directory'
        required: true
        type: string
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: v${{ inputs.version }}

      - name: Setup Node and Build
        uses: ./.github/actions/setup-node-build
        with:
          build-command: 'npm run build --workspaces --if-present'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish Plugin
        if: "!contains(inputs.version, '-dev')"
        run: npm publish --workspace plugins/${{ inputs.plugin_name }} --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
